### PR TITLE
Enh parsimonious

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by klauer** [comment]
Cool, thanks @tacaswell!

**Comment by tacaswell** [comment]
@klauer I think I am happy with this.  Got the the test coverage up, can generate code + the `txt` files the existing parser generates.

**Comment by tacaswell** [comment]
The grammar is still both too detailed and to generic (with how the entries inside of the fields are parsed) and many of the constructs are treated as no-ops (function, variable, device, ...) but I don't (yet) care about those things ;).

**Comment by klauer** [comment]
It's been fun watching your progress with this. It looks great now - with even a full test suite (and upstream ophyd fixes). Thanks!

**Pull request merged**
