### PR TITLE
ENH: first draft of *.db file and template string parsing

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by klauer** [comment]
Reference code from chat

```python 
from recordwhat.parsers.db_parsimonious import db_grammar, dbWalker, template_grammar, TemplateWalker
from recordwhat.registry import get_record_class
from recordwhat.util import read_file
from pathlib import Path
import os

def find_db(start_path, include_path='', out_path=None):
   if out_path is not None:
       out_path = Path(out_path)
       os.makedirs(out_path, exist_ok=True)

   dw = dbWalker()
   out_strs = []
   for root, dirs, files in os.walk(start_path):
       root = Path(root)
       interesting_files = [f for f in files if f[-3:] == '.db']

       for f in interesting_files:
           dev_strs = ['class {}(Device):'.format(f[:-3].capitalize)]

           print(root / f)
           recs = dw.visit(db_grammar.parse(read_file(root / f, path=include_path)))
           r_class = get_record_class(r.rtype).__name__
           nm = r.pvname[r.pvname.rfind(':'):].lower()
           for r in recs:
               cmp_str = '    {} = Cpt({}, {})'.format(nm, r,
```

```python
from recordwhat.parsers.dbd_parsimonious import dbd_grammar, RecordWalker, generate_all
from recordwhat.registry import get_record_class
from recordwhat.util import read_file
from pathlib import Path
import os

def find_dbd(start_path, include_path='', out_path=None):
   if out_path is not None:
       out_path = Path(out_path)
       os.makedirs(out_path, exist_ok=True)

   to_generate = []
   rw = RecordWalker()
   for root, dirs, files in os.walk(start_path):
       root = Path(root)
       interesting_files = [f for f in files if f[-3:] == 'dbd']
       for f in interesting_files:
           print(root / f)
           recs = rw.visit(dbd_grammar.parse(read_file(root / f, path=include_path)))

           for r in recs.values():
               try:
                   get_record_class(r.name)
               except ValueError:
                   to_generate.append(r)

   to_generate = list({r.name: r for r in to_generate}.values())
   cls_str = '\n'.join(generate_all(to_generate)) + '\n'
   try:
       exec(cls_str, globals())
   except SyntaxError:
       print('failed on {} from {}'.format(r.name, root / f))

   if out_path is not None:
       with open(out_path / '20-maia.py'.format(), 'wt') as fout:
           print(fout.name)
           fout.write(cls_str)
```

**Comment by tacaswell** [comment]
```python
#from recordwhat.parsers.db_parsimonious import (
#    db_grammar, dbWalker, template_grammar, TemplateWalker)
from recordwhat.util import read_file
import attr

f_blog = '/tmp/SR05ID01FS01/db/blogioc.db'
f_kand = '/tmp/SR05ID01FS01/db/kandinskiVars.db'




def injest_db_file(fname):
    dw = dbWalker()
    return dw.visit(db_grammar.parse(read_file(fname)))

recs_blog = injest_db_file(f_blog)
recs_kand = injest_db_file(f_kand)

def stream_components(recs, nm_maker):
    tw = TemplateWalker()

    for r in recs:
        rtype = r.rtype
        pv_template = tw.visit(template_grammar.parse(r.pvname))
        pv = pv_template.val.format(**{k:'' for k in pv_template.keys})
        nm = nm_maker(pv)
        yield '{} = Cpt({}, {})'.format(nm, rtype, pv)

```

is also relevant

**Comment by tacaswell** [comment]
force-pushed to fix up commit ownership

**Comment by tacaswell** [comment]
I think the results of `stream_components` gets feed into `recordwhat.parser.generate.generate`

**Comment by klauer** [comment]
Thanks @tacaswell!

**Comment by tacaswell** [comment]
Who needs tests? --Leeroy Jenkins

**Pull request merged**
